version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - goheader
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    goheader:
      template-path: copyright.tmpl
    gosec:
      excludes:
        - G101  # hardcoded credentials (variable names, not actual secrets)
        - G110  # potential DoS via decompression bomb
        - G112  # potential slowloris attack
        - G114  # net/http serve without timeouts
        - G115  # integer overflow conversion
        - G306  # WriteFile permissions
        - G402  # TLS settings (intentionally configurable)
        - G404  # weak random (used for shuffling, not crypto)
    misspell:
      locale: US,UK
    staticcheck:
      checks:
        - ST1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - .*_test\.go
      - .*test\.go
      - testing
      - src/jobservice/mgt/mock_manager.go
      - server/v2.0/models
      - server/v2.0/restapi
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
    goimports:
      local-prefixes:
        - github.com/goharbor/harbor
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - .*_test\.go
      - .*test\.go
      - testing
      - src/jobservice/mgt/mock_manager.go
      - server/v2.0/models
      - server/v2.0/restapi
